### PR TITLE
Release 2024-10-02

### PR DESCRIPTION
**Pull request by mihnea-radulescu**

### CODE REVIEW

**Comment by hfiguiere** [comment]
adding back the file we asked to put upstream? Why?

**Comment by mihnea-radulescu** [comment]
Hi @hfiguiere,

Thank you for the feedback!

I like to keep all of the flatpak-related files encapsulated in the repository itself, as it makes managing things easier for me, without interfering with the build server.

I do the same in my other flatpak repositories, such as in [ImageFan Reloaded](https://github.com/flathub/io.github.mihnea_radulescu.imagefanreloaded).

**Comment by hfiguiere** [comment]
> I like to keep all of the flatpak-related files

They are NOT flatpak specific at all. They are part of the much older XDG standard. During the review we insisted they'd be mamaged upstream, and back dooring re-adding them is basically...

**Comment by hfiguiere** [comment]
> I do the same in my other flatpak repositories, such as in [ImageFan Reloaded](https://github.com/flathub/io.github.mihnea_radulescu.imagefanreloaded).

TWO WRONGS DON'T MAKE A RIGHT.

**Comment by mihnea-radulescu** [comment]
I see, ok.

I've removed the data folder here and, with a future release, will also remove it from the **ImageFan Reloaded** repository.

**Pull request merged**
